text_generator/__init__.py
from flask import Flask
from .routes import generator
# 15. We need to import the modules in our init file for flask
# !!! Not needed
# from .model import *
# from .sample import *
# from .encoder import *

# 4. Explain how to initialize a flask app and talk about flask
# the settings file,  __name__ and config_file
def create_app(config_file='settings.py'):
    # EXPLAIN HOW WE NEED THE STATIC FOLDER FOR IMAGES (WALLEY IN THIS CASE)
    app = Flask(__name__, static_url_path = "/tmp", static_folder = "tmp")

    app.config.from_pyfile(config_file)
    # 6. Register blueprint explain
    app.register_blueprint(generator)
    return app

text_generator/routes.py
from flask import Blueprint, render_template, request, redirect
from .generator import ai

generator = Blueprint('generator', __name__)

@generator.route('/')
def index():
    # 18. Now add route index 
    return render_template('index.html')

@generator.route('/analyze', methods=['POST'])
def analyze():
    # 7. Explain the render template and import and also how it finds the index
    # 8. Also explain how we need to create a template now
    title = request.form['title']
    text = ai.generate_text(title)

    return render_template('index.html', text=text)

# 11. Now lets go and train our model for text generation / Download and Extract the GPT2 Finetuning repo
# Link(https://github.com/nshepperd/gpt-2)    

# STEPS FOR TRAINING THE MODEL
# -> MOVE encode.py /train.py / train-horovod.py to the src folder
# -> pip install -r requirements.txt
# -> python download_model.py 117M
# -> MOVE models folder to src 
# -> ADD training.txt file to src Link(https://www.looper.com/162409/the-entire-star-wars-story-finally-explained/)
# -> python encode.py training.txt training.npz (encoded model which the training script will use)
# -> python train.py --dataset training.npz
# -> CREATE a new model in the models folder which is just a copy of our 117M
# -> COPY from src/checkpoints/run1 to the new copy thats 117M and overwrite the files
# -> ALSO adapt all the imports so that the right model is used(in interactive_conditional_samples)
# -> RUN with python src/interactive_conditional_samples.py --top_k 40 --model_name <our model name> --length 25 
# -> IMPORTANT NOTE THIS WILL ONLY WORK WITH TENSORFLOW !!! 1.8 !!! and not with 2.2
# -> IMPORTANT NOTE ALSO ADAPT THE train.py TO SAVE AND HAVE A MAX NUMBER OF ITERATIONS
# 12. Now that this is finished we need to think of a way to use our model in our route and return the result 
# to the index.html

# 13. Now lets use the code from the interactive code sample in our generator.py
# 14. Alos move model, smaple and encoder to the same directory

text_generator/templates/index.html
<!-- # 9. Explain how this is going to call the route -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<!-- Explain the forms styles and how we are passing data from the template to the route -->
<style>
  .courseTitle{
    background-color: #f5f5f5;
    border:1px solid #C7CDD1;
    padding:0.5em 1em;
    font-size:28px;
  }
  button{
    color:#0074db;
    border-radius:8px;
    padding:10px;
    border-color: #0074db;
    border-radius:15px;
    background-color: #ffffff;
  }
  button:hover{
    color:white;
    background-color:#0074db;
  }
</style>
<div style="display: flex; flex-direction: row; width: 100%; height: 100%; background-color: rgb(255, 255, 255);">
  <div>
    <form style="max-width: 800px; margin: 50px; justify-self: center;" method="POST" action="{{ url_for('generator.analyze') }}">
      <div class="form-group">
        <label for="title" class = "courseTitle">Course Description Generator</label>
        <input type="text" style="height: 60px; font-size: 20px;" class="form-control" placeholder="Enter Starting Phrase" name="title"/>
      </div>
      
      <button type="submit">Submit</button>
    </form>
    <p class="text-left" style="margin: 50px; padding: 10px; border-radius: 8px; font-size: 18px; background-color: #f4f4f4; max-width: 100%;">
      {{ text }}
    </p>
  </div>
  <!-- <div>
    <img style="margin: 100px; border: 0;" alt="WALLEY" width="750" height="600" src="/tmp/walley.png" />
  </div> -->
</div>